### ISSUE TITLE
ValueError with certain input file

### ISSUE THREAD

**Issue by lodersky** [tum-ens/geoclustering#28]
Running the code with a certain input file (attached) gives the following error message:
Traceback (most recent call last):
```
  File ".../geoclustering/code/runme.py", line 18, in <module>
    k_means_clustering(paths, param)
  File "...\geoclustering\code\lib\kmeans_functions.py", line 340, in k_means_clustering
    optimum_no_of_clusters_for_raster = identify_opt_number_of_clusters(paths, param, i, size_of_raster, std_of_raster)
  File "...\geoclustering\code\lib\kmeans_functions.py", line 135, in identify_opt_number_of_clusters
    optimum_no_of_clusters_for_raster = int(np.ceil(group_by_part.loc[part, "share"] * maximum_no_of_clusters))
ValueError: cannot convert float NaN to integer
```
Would be helpful to get feedback on the error. The example files of the workshop are working fine. 

[Grundwassertemperatur.zip](https://github.com/tum-ens/geoclustering/files/3896461/Grundwassertemperatur.zip)

**Comment by kais-siala** [comment]
For that, we need to save the TIF files (at the cuting stage) as float rasters.
